'use client';

import { Assets, AssetsManifest } from 'pixi.js';
import { useCallback, useEffect, useRef, useState } from 'react';

export function useAssets() {
  const assetsManifest = useRef<AssetsManifest>({ bundles: [] });
  const [loadedBundles, setLoadedBundles] = useState<string[]>([]);

  /** Load assets bundles that have not been loaded yet */
  const loadBundles = useCallback(
    async (bundles: string | string[]) => {
      if (typeof bundles === 'string') bundles = [bundles];

      // Check bundles requested if they exists
      for (const bundle of bundles) {
        if (!assetsManifest.current.bundles.find(b => b.name === bundle)) {
          throw new Error(`[Assets] Invalid bundle: ${bundle}`);
        }
      }

      // Filter out bundles already loaded
      const loadList = bundles.filter(
        bundle => !loadedBundles.includes(bundle)
      );

      // Skip if there is no bundle left to be loaded
      if (!loadList.length) return;

      // Load bundles
      await Assets.loadBundle(loadList);

      // Append loaded bundles to the loaded list
      setLoadedBundles([...loadedBundles, ...loadList]);
      console.log('[Assets] Load:', loadList.join(', '));
    },
    [loadedBundles]
  );

  /** Check if all bundles are loaded, return false if any of them is not loaded yet  */
  const areBundlesLoaded = useCallback(
    (bundles: string[]) => {
      for (const name of bundles) {
        // Return false if a single bundle is not present in the loaded list
        if (!loadedBundles.includes(name)) {
          return false;
        }
      }

      // All provided bundles are loaded
      return true;
    },
    [loadedBundles]
  );

  useEffect(() => {
    const load = async () => {
      if (assetsManifest.current.bundles.length) return;

      // Load assets manifest
      assetsManifest.current = await fetchAssetsManifest(
        '/react-puzzling-potions/assets/assets-manifest.json'
      );

      // Init PixiJS assets with this asset manifest
      await Assets.init({
        manifest: assetsManifest.current,
        basePath: 'assets',
      });

      // Load assets for the load screen
      await loadBundles('preload');

      // List all existing bundles names
      const allBundles = assetsManifest.current.bundles.map(item => item.name);

      // Start up background loading of all bundles
      Assets.backgroundLoadBundle(allBundles);
    };
    load();
  }, [loadBundles]);

  return {
    loadedBundles,
    loadBundles,
    areBundlesLoaded,
  };
}

/** Load the assets json manifest generated by assetpack */
async function fetchAssetsManifest(url: string) {
  const response = await fetch(url);
  const manifest = await response.json();
  if (!manifest.bundles) {
    throw new Error('[Assets] Invalid assets manifest');
  }
  return manifest;
}
